WITH CTE AS
(
SELECT O_ORDERDATE ORDERDATE,
YEAR(O_ORDERDATE) YEAR,
MONTH(O_ORDERDATE) MONTH,
DATE(O_ORDERDATE) DATE,
DAY(O_ORDERDATE) DAY,
DAYNAME(O_ORDERDATE) DAYNAME,
CASE WHEN DAYNAME(O_ORDERDATE) IN ('Sat','Sun') THEN 'WEEKEND' ELSE 'WEEKDAY' END AS DAY_TYPE,
{{datefunction('O_ORDERDATE')}}  AS MONSTATS

 from 
{{ source('demo', 'orders') }}

)
SELECT * FROM CTE
